dist: trusty
sudo: required
language: bash
before_install:
- curl https://raw.githubusercontent.com/express42/otus-homeworks/2018-05/run.sh | bash
notifications:
  slack:
    secure: KciWiLRQWQW915p0VN5eAcWonp3O05btS2tbTyNQF3egDqBG4pllGfz5wvp+oddbTJX3uQuKH2JxAFEo6msuanydRiZLReWAyKhsesrZc6xY3KE8Sia2xjk9SRgmfmmaDdCcOwnDw7sulmvtrE8Q3rjC04D3oanTpGoqPXjntEizfoksqZLnYPT6C4zttM7vJ/7kwPfC6XeM7qro7hjf/mDe3xw5qNfnB6i66oE7oXm/4udDUyGUUX0z3hTKpyd2N0g7xCvKKK35KTejVj5ssejPAfuBzz9AC1PmfkP4eZH67wO9rfXVHr/9V1PQpVjZIDgYUcOJIUm0ceUuXB0r7sC9OH2PLh1UPgTnF7wrp3Ey3SXwUuJWSnQ4ulQAMvke5UZx6KOYY3rhiCmZkn4omvqGE6voFIg2s15oxxjSpVkjqIt52jjoZe3RX9uGD607P+dAp94wQvuEf8W3Qa1QyplLqDuiIXHlRDE4n2BZPI3YEujCqh352P+VPrCnBUpPF6KUm8xZPG4oW+k7gG2Ye3WHudg9TsSn8PIYR7ucTJZiK4O/5o0IWWBaxWQ35XVk8sZfxGEfDdYdz8tWBYIOdAydnR/j1vF1jb6IBHXQwlL8xx6TzlqZ37vIyJZ32ozkB74aVYLnQg+IPtxid5DrbcbifvehZum+9H2JGcnX9rU=
