---
# tasks file for db

- name: Show info about the env this host belongs to
  debug:
    msg: "This host is in {{ env|default('local') }} environment!!!"

- include: install_mongo.yml
- include: config_mongo.yml
